### ISSUE TITLE
Can not find the lib sdk at Windows

### ISSUE THREAD

**Issue by roter-mann** [DoubangoTelecom/ultimateALPR-SDK#12]
Hi,
I want to try out your solution but I can not find a library for windows. At CMake I get the folllowing Error:

CMake Error at samples/c++/benchmark/CMakeLists.txt:6 (add_subdirectory):
  add_subdirectory given source
  "C:/projects/ultimateALPR-SDK/samples/c++/benchmark/../../../../SDK_dev/lib"
  which is not an existing directory.

CMake Error at samples/c++/recognizer/CMakeLists.txt:6 (add_subdirectory):
  add_subdirectory given source
  "C:/projects/ultimateALPR-SDK/samples/c++/recognizer/../../../../SDK_dev/lib"
  which is not an existing directory.

Also you reference at the c++ sample project to the missing folders: <ProjectReference Include="..\..\..\..\SDK_dev\lib\ultimateALPR-SDK.vcxproj">

Can you add the folder and library at "SDK_dev/lib"  to your git repo, please?

**Comment by DoubangoTelecom** [comment]
Windows is supported but for now only Android and Raspberry Pi binaries are released. https://www.doubango.org/SDKs/anpr/docs/Architecture_overview.html#supported-operating-systems

**Comment by roter-mann** [comment]
Thank you for your help. Do you know when you will release the library for x86/x64 for Windows/Linux?

I have also tried out your samples with Android Emulator with SDK 28 on my Windows x64 pc. First I getting the error: E/linker: "/data/app/org.doubango.ultimateAlpr-jZsBdaj0YSbeEFD9OHk4oA==/lib/x86/libultimateALPR_SDK.so" has text relocations

After setting the targetSdkVersion to 22 ( >= 23 cannot run libraries with text relocations) I get the following error:
ava.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__atomic_load_8" referenced by "/data/app/org.doubango.ultimateAlpr-Qxgme8I7tf9V2L4sCIOgpA==/lib/x86/libtensorflowlite_gpu_gl.so"...

Can you help me please?

**Comment by DoubangoTelecom** [comment]
Adding more platforms means more support to provide and this is why we're focusing on ARM for now. Windows is our host dev-env and our cloud (https://www.doubango.org/webapps/alpr/) runs on Ubuntu 18. So, Linux/Windows are supported but not yet released. X86/X64 platforms no longer link to tensorflow-lite. "/lib/x86/libtensorflowlite_gpu_gl.so" not part of the latest releases. Try to update your code.

**Comment by DoubangoTelecom** [comment]
I've tried the latest version with "Nexus 9 API 24" emulator (x86). It's horribly slow as expected but it's working fine.

**Comment by brunoaduarte** [comment]
> I've tried the latest version with "Nexus 9 API 24" emulator (x86). It's horribly slow as expected but it's working fine.

I've tried running the code on a "Nexus 9 API 24" emulator (x86) but i get these errors. Do you know how to fix this?

```
2020-02-20 00:38:18.380 4493-4493/? I/art: Not late-enabling -Xcheck:jni (already on)
2020-02-20 00:38:18.380 4493-4493/? W/art: Unexpected CPU variant for X86 using defaults: x86
2020-02-20 00:38:18.429 4493-4493/? I/org.doubango.ultimateAlpr.AlprVideoParallelActivity: onCreate org.doubango.ultimateAlpr.AlprVideoParallelActivity@252f3fd
2020-02-20 00:38:18.429 4493-4493/? I/org.doubango.ultimateAlpr.common.AlprActivity: onCreate org.doubango.ultimateAlpr.AlprVideoParallelActivity@252f3fd
2020-02-20 00:38:18.435 4493-4493/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
2020-02-20 00:38:18.446 4493-4493/? I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void org.doubango.ultimateAlpr.common.AlprActivity.onCreate(android.os.Bundle) (AlprActivity.java:96)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void org.doubango.ultimateAlpr.AlprVideoParallelActivity.onCreate(android.os.Bundle) (AlprVideoParallelActivity.java:210)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6662)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1118)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2599)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2707)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1460)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void android.os.Looper.loop() (Looper.java:154)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:866)
2020-02-20 00:38:18.446 4493-4493/? I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:756)
2020-02-20 00:38:18.446 4493-4493/? I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/org.doubango.ultimateAlpr-2/base.apk"],nativeLibraryDirectories=[/data/app/org.doubango.ultimateAlpr-2/lib/x86, /data/app/org.doubango.ultimateAlpr-2/base.apk!/lib/x86, /system/lib, /vendor/lib]]
2020-02-20 00:38:18.446 4493-4493/? I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void org.doubango.ultimateAlpr.common.AlprActivity.onCreate(android.os.Bundle) (AlprActivity.java:96)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void org.doubango.ultimateAlpr.AlprVideoParallelActivity.onCreate(android.os.Bundle) (AlprVideoParallelActivity.java:210)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6662)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1118)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2599)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2707)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1460)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void android.os.Looper.loop() (Looper.java:154)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:866)
2020-02-20 00:38:18.448 4493-4493/? I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:756)
2020-02-20 00:38:18.497 4493-4493/? E/linker: /data/app/org.doubango.ultimateAlpr-2/lib/x86/libultimateALPR_SDK.so: has text relocations
2020-02-20 00:38:18.498 4493-4493/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.doubango.ultimateAlpr, PID: 4493
    java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/org.doubango.ultimateAlpr-2/lib/x86/libultimateALPR_SDK.so: has text relocations
        at java.lang.Runtime.loadLibrary0(Runtime.java:977)
        at java.lang.System.loadLibrary(System.java:1530)
        at org.doubango.ultimateAlpr.Sdk.ultimateAlprSdkJNI.<clinit>(ultimateAlprSdkJNI.java:14)
        at org.doubango.ultimateAlpr.Sdk.ultimateAlprSdkJNI.new_UltAlprSdkParallelDeliveryCallback(Native Method)
        at org.doubango.ultimateAlpr.Sdk.UltAlprSdkParallelDeliveryCallback.<init>(UltAlprSdkParallelDeliveryCallback.java:54)
        at org.doubango.ultimateAlpr.common.AlprActivity$MyUltAlprSdkParallelDeliveryCallback.<init>(AlprActivity.java:48)
        at org.doubango.ultimateAlpr.common.AlprActivity$MyUltAlprSdkParallelDeliveryCallback.newInstance(AlprActivity.java:77)
        at org.doubango.ultimateAlpr.common.AlprActivity.onCreate(AlprActivity.java:107)
        at org.doubango.ultimateAlpr.AlprVideoParallelActivity.onCreate(AlprVideoParallelActivity.java:210)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

**Comment by DoubangoTelecom** [comment]
Version 2.7.0 makes Windows binaries public:
- C++ samples: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B
- C# sample: https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/csharp
