### ISSUE TITLE
Failed to match tensorflow fingerprint

### ISSUE THREAD

**Issue by quinteroqca** [DoubangoTelecom/ultimateALPR-SDK#142]
Hi @DoubangoTelecom :

I am trying to run the python wrappers on my x86_64 Linux system.

I am in to this directory : /ultimateALPR-SDK/binaries/linux/x86_64

I found out that some file is missing from the tensorflow library
- libtensorflow_framework.so
- libtensorflow.so.1

so I use the ones in the <a href='https://www.tensorflow.org/install/lang_c'>Nightly Libtensorflow C packages</a>.

The build seems to have gone well

```
$> python ${ALPR_ROOT}/python/setup.py build_ext --inplace -v 

Your platform: linux
running build_ext
building '_ultimateAlprSdk' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I../../../c++ -I${HOME}/.local/share/virtualenvs/ultimateALPR-SDK-SUVeTM_r/include -I/usr/include/python3.9 -c ${ALPR_ROOT}/python/ultimateALPR-SDK-API-PUBLIC-SWIG_python.cxx -o build/temp.linux-x86_64-3.9${ALPR_ROOT}/python/ultimateALPR-SDK-API-PUBLIC-SWIG_python.o
gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fno-semantic-interposition -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-x86_64-3.9${ALPR_ROOT}/python/ultimateALPR-SDK-API-PUBLIC-SWIG_python.o -L. -L/usr/lib -lultimate_alpr-sdk -o ${ALPR_LINUX}/_ultimateAlprSdk.so
```
and creates the "_ultimateAlprSdk.so" file, but when I try to test it doesn't recognized the tensorflow: `Failed to match tensorflow fingerprint`

```
$> PYTHONPATH=$PYTHONPATH:${ALPR_LINUX}:${ALPR_ROOT}/python LD_LIBRARY_PATH=${ALPR_LINUX}:$LD_LIBRARY_PATH python ${ALPR_ROOT}/samples/python/recognizer/recognizer.py --image ${ALPR_ROOT}/assets/images/lic_us_1280x720.jpg --assets ${ALPR_ROOT}/assets


*[COMPV INFO]: [UltAlprSdkEngine] Call: init
*[COMPV INFO]: [UltAlprSdkEngine] jsonConfig: {"debug_level": "info", "debug_write_input_image_enabled": false, "debug_internal_data_path": ".", "num_threads": -1, "gpgpu_enabled": true, "max_latency": -1, "klass_vcr_gamma": 1.5, "detect_roi": [0, 0, 0, 0], "detect_minscore": 0.1, "car_noplate_detect_min_score": 0.8, "pyramidal_search_enabled": true, "pyramidal_search_sensitivity": 0.28, "pyramidal_search_minscore": 0.3, "pyramidal_search_min_image_size_inpixels": 800, "recogn_minscore": 0.3, "recogn_score_type": "min", "assets_folder": "${ALPR_ROOT}/assets", "charset": "latin", "car_noplate_detect_enabled": false, "ienv_enabled": false, "openvino_enabled": false, "openvino_device": "CPU", "klass_lpci_enabled": false, "klass_vcr_enabled": false, "klass_vmmr_enabled": false, "klass_vbsr_enabled": false, "license_token_file": "", "license_token_data": ""}
*[COMPV INFO]: /!\ Code in file '/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_public_engine.cxx' in function 'init' starting at line #77: Not optimized -> Code not built for mobile devices but for clouds. Are you sure this is what you want?
*[COMPV INFO]: [UltAlprSdkEngine] **** Copyright (C) 2011-2021 Doubango Telecom <https://www.doubango.org> ****
ultimateALPR-SDK <https://github.com/DoubangoTelecom/ultimateALPR-SDK> version 3.3.0

*[COMPV INFO]: [CompVBase] Initializing [base] modules (v 1.0.0, nt -1)...
*[COMPV INFO]: [CompVBase] sizeof(compv_scalar_t)= #8
*[COMPV INFO]: [CompVBase] sizeof(float)= #4
*[COMPV INFO]: Initializing window registery
*[COMPV INFO]: [ImageDecoder] Initializing image decoder...
*[COMPV INFO]: [CompVCpu] H: 'GenuineIntel', S: '', M: '142', MN: 'Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz'
*[COMPV INFO]: [CompVBase] CPU features: (intel);[x86];[x64];mmx;sse;sse2;sse3;ssse3;sse41;sse42;avx;avx2;fma3;erms;bmi1;bmi2;popcnt;cmov;aes;rdrand;
*[COMPV INFO]: [CompVBase] CPU cores: #8
*[COMPV INFO]: [CompVBase] CPU cache1: line size: #64B, size :#32KB
*[COMPV INFO]: [CompVBase] CPU Phys RAM size: #15849GB
*[COMPV INFO]: [CompVBase] CPU endianness: LITTLE
*[COMPV INFO]: [CompVBase] Binary type: X86_64
*[COMPV INFO]: [CompVBase] Intrinsic enabled
*[COMPV INFO]: [CompVBase] Assembler enabled
*[COMPV INFO]: [CompVBase] Code built with option /arch:SSE
*[COMPV INFO]: [CompVBase] Code built with option /arch:SSE2
*[COMPV INFO]: [CompVBase] OS name: Generic Linux
*[COMPV INFO]: [CompVBase] Math Fast Trig.: true
*[COMPV INFO]: [CompVBase] Math Fixed Point: true
*[COMPV INFO]: [CompVMathExp] Init
*[COMPV INFO]: [CompVBase] Default alignment: #64
*[COMPV INFO]: [CompVBase] Best alignment: #64
*[COMPV INFO]: [CompVBase] Heap limit: #811515KB (#792MB)
*[COMPV INFO]: [CompVParallel] Initializing [parallel] module...
*[COMPV INFO]: /!\ Code in file '/home/ultimate/compv/base/compv_mem.cxx' in function 'CompVMemZero_C' starting at line #504: Not optimized -> No SIMD implementation found
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=0,set=useless, threadId:0x7fba5ac6c640, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=1,set=useless, threadId:0x7fba5a46b640, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=2,set=useless, threadId:0x7fba59c6a640, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=3,set=useless, threadId:0x7fba59469640, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=4,set=useless, threadId:0x7fba58c68640, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=5,set=useless, threadId:0x7fba58467640, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=6,set=useless, threadId:0x7fba57c66640, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVThreadDispatcher] Thread dispatcher created with #8 threads/#8 cores
*[COMPV INFO]: [CompVParallel] [Parallel] module initialized
*[COMPV INFO]: [CompVBase] [Base] modules initialized
*[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=7,set=useless, threadId:0x7fba57465640, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVCore] Initializing [core] module (v 1.0.0)...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 1 and name = 'FAST (Features from Accelerated Segment Test)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 8 and name = 'ORB (Oriented FAST and Rotated BRIEF)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 27 and name = 'Sobel edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 28 and name = 'Scharr edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 29 and name = 'Prewitt edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 20 and name = 'Canny edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 30 and name = 'Hough standard (STD)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 31 and name = 'Kernel-based Hough transform (KHT)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 41 and name = 'Standard Histogram of oriented gradients (S-HOG)'...
*[COMPV INFO]: [CompVMatcher] Registering matcher factory with id = 0 and name = 'Brute force matcher'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 1 and name = 'PLSL (Parallel Light Speed Labeling)'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 19 and name = 'LMSER (Linear Time Maximally Stable Extremal Regions)'...
*[COMPV INFO]: [CompVGL] Initializing [gl] module (v 1.0.0)...
*[COMPV INFO]: [CompVGL] GL module initialized
*[COMPV INFO]: [CompVGpu] Initializing [gpu] module (v 1.0.0)...
*[COMPV INFO]: [CompVCamera] Initializing [camera] module (v 1.0.0)...
*[COMPV INFO]: [CompVDrawing] Initializing [drawing] module (v 1.0.0)...
*[COMPV INFO]: [CompVDrawing] /!\ No jpeg decoder found
*[COMPV INFO]: [CompVDrawing] Drawing module initialized
*[COMPV INFO]: [CompVGpu] GPU enabled: true
*[COMPV INFO]: /!\ Code in file '/home/ultimate/ultimateBase/lib/source/ultimate_base_engine.cxx' in function 'init' starting at line #75: Not optimized for GPU -> GPGPU computing not enabled or deactivated
*[COMPV INFO]: [UltBaseOpenCL] Trying to load [libOpenCL.so]
*[COMPV INFO]: [UltBaseOpenCL] Failed to load [libOpenCL.so]
*[COMPV INFO]: [UltOcrEngine] Tensorflow version: 2.4.0
*[COMPV INFO]: [UltAlprSdkEnginePrivate] **** Copyright (C) 2011-2021 Doubango Telecom <https://www.doubango.org> ****
You're using an unlicensed version of ultimateALPR-SDK <https://github.com/DoubangoTelecom/ultimateALPR-SDK>
without the rights to include the SDK in any form of commercial product.
*[COMPV INFO]: [UltAlprSdkEnginePrivate] IC took 69 millis
***[COMPV ERROR]: function: "init()" 
file: "/home/ultimate/ultimateALPR/SDK_dev/lib/source/ultimate_alpr_sdk_public_engine.cxx" 
line: "131" 
message: [UltAlprSdkEngine] Failed to match tensorflow fingerprint
[PythonRecognizer] Init: failed -> Failed to match tensorflow fingerprint
Traceback (most recent call last):
  File "${ALPR_ROOT}/samples/python/recognizer/recognizer.py", line 131, in <module>
    checkResult("Init", 
  File "${ALPR_ROOT}/samples/python/recognizer/recognizer.py", line 68, in checkResult
    assert False
AssertionError
*[COMPV INFO]: [Thread] Thread with id=0x7fba5ac6c640 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fba5ac6c640) - EXIT
*[COMPV INFO]: Thread with id=0x7fba5ac6c640 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fba5ac6c640 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0x7fba5a46b640 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fba5a46b640) - EXIT
*[COMPV INFO]: Thread with id=0x7fba5a46b640 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fba5a46b640 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0x7fba59c6a640 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fba59c6a640) - EXIT
*[COMPV INFO]: Thread with id=0x7fba59c6a640 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fba59c6a640 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0x7fba59469640 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fba59469640) - EXIT
*[COMPV INFO]: Thread with id=0x7fba59469640 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fba59469640 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0x7fba58c68640 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fba58c68640) - EXIT
*[COMPV INFO]: Thread with id=0x7fba58c68640 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fba58c68640 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0x7fba58467640 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fba58467640) - EXIT
*[COMPV INFO]: Thread with id=0x7fba58467640 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fba58467640 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0x7fba57c66640 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fba57c66640) - EXIT
*[COMPV INFO]: Thread with id=0x7fba57c66640 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fba57c66640 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0x7fba57465640 will join
*[COMPV INFO]: [CompVAsyncTask11] run(threadId:0x7fba57465640) - EXIT
*[COMPV INFO]: Thread with id=0x7fba57465640 will join
*[COMPV INFO]: [Thread] ***Thread with id=0x7fba57465640 destroyed***
```

This is my environment
```
$> export ALPR_ROOT=path_to_the/ultimateALPR-SDK
$> export ALPR_LINUX=${ALPR_ROOT}/binaries/linux/x86_64
$> cd ${ALPR_LINUX}
$> python --version

Python 3.9.2

$> pip freeze

certifi==2020.12.5
chardet==4.0.0
cPython==0.0.6
Cython==0.29.22
idna==2.10
Pillow==8.2.0
pymongo==3.11.3
requests==2.25.1
urllib3==1.26.4
```

Would be glad if you can help me out resolve the issue.

**Comment by DoubangoTelecom** [comment]
Tensorflow libraries are at https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/c%2B%2B#gpu-acceleration-tensorflow-linux
