### ISSUE TITLE
Can't open the video

### ISSUE THREAD

**Issue by asuzairy** [DoubangoTelecom/ultimateALPR-SDK#296]
C:\Users\USER\Documents\ultimateALPR-SDK\samples\python\recognizer>python recognizer.py --video "C:\Users\USER\Videos\test_video2.mp4" --assets "../../../assets"
*[COMPV INFO]: [UltAlprSdkEngine]Call: ultimateAlprSdk::UltAlprSdkEngine::init
*[COMPV INFO]: [UltAlprSdkEngine]jsonConfig: {"debug_level": "info", "debug_write_input_image_enabled": false, "debug_internal_data_path": ".", "num_threads": -1, "gpgpu_enabled": true, "max_latency": -1, "klass_vcr_gamma": 1.5, "detect_roi": [0, 0, 0, 0], "detect_minscore": 0.1, "car_noplate_detect_min_score": 0.8, "pyramidal_search_enabled": true, "pyramidal_search_sensitivity": 0.28, "pyramidal_search_minscore": 0.3, "pyramidal_search_min_image_size_inpixels": 800, "recogn_rectify_enabled": true, "recogn_minscore": 0.3, "recogn_score_type": "min", "assets_folder": "../../../assets"}
*[COMPV INFO]: [UltAlprSdkEngine]**** Copyright (C) 2011-2024 Doubango Telecom <https://www.doubango.org> ****
ultimateALPR-SDK <https://github.com/DoubangoTelecom/ultimateALPR-SDK> version 3.14.1

*[COMPV INFO]: [CompVBase] Initializing [base] modules (v 1.0.0, nt -1)...
*[COMPV INFO]: [CompVBase] sizeof(compv_scalar_t)= #8
*[COMPV INFO]: [CompVBase] sizeof(float)= #4
*[COMPV INFO]: [CompVBase] Windows dwMajorVersion=10, dwMinorVersion=0
*[COMPV INFO]: Initializing window registery
*[COMPV INFO]: [ImageDecoder] Initializing image decoder...
*[COMPV INFO]: [CompVCpu] H: 'GenuineIntel', S: '', M: '', MN: ''
*[COMPV INFO]: [CompVBase] CPU features: (intel);[x86];[x64];mmx;sse;sse2;sse3;ssse3;sse41;sse42;avx;avx2;fma3;erms;bmi1;bmi2;popcnt;cmov;aes;rdrand;
*[COMPV INFO]: [CompVBase] CPU cores: online=#4, conf=#4
*[COMPV INFO]: [CompVBase] CPU cache1: line size: #64B, size :#32KB
*[COMPV INFO]: [CompVBase] CPU Phys RAM size: #8047GB
*[COMPV INFO]: [CompVBase] CPU endianness: LITTLE
*[COMPV INFO]: [CompVBase] Binary type: X86_64
*[COMPV INFO]: [CompVBase] Intrinsic enabled
*[COMPV INFO]: [CompVBase] Assembler enabled
*[COMPV INFO]: [CompVBase] OS name: Windows
*[COMPV INFO]: [CompVBase] Math Fast Trig.: true
*[COMPV INFO]: [CompVBase] Math Fixed Point: true
*[COMPV INFO]: [CompVMathExp] Init
*[COMPV INFO]: [CompVBase] Default alignment: #64
*[COMPV INFO]: [CompVBase] Best alignment: #64
*[COMPV INFO]: [CompVBase] Heap limit: #412030KB (#402MB)
*[COMPV INFO]: [CompVParallel] Initializing [parallel] module...
*[COMPV INFO]: /!\ Code in file 'compv_mem.cxx' in function 'compv::CompVMemZero_C' starting at line #508: Not optimized -> No SIMD implementation found
*[COMPV INFO]: [CompVThreadDispatcher] Thread dispatcher created with #4 threads/#4 cores
*[COMPV INFO]: [CompVParallel] [Parallel] module initialized
*[COMPV INFO]: [CompVBase] [Base] modules initialized
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=1,set=useless, threadId:00000000000017CC, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=0,set=useless, threadId:0000000000002F74, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=2,set=useless, threadId:0000000000003144, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVCore] Initializing [core] module (v 1.0.0)...
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=3,set=useless, threadId:0000000000003FBC, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 1 and name = 'FAST (Features from Accelerated Segment Test)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 8 and name = 'ORB (Oriented FAST and Rotated BRIEF)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 27 and name = 'Sobel edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 28 and name = 'Scharr edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 29 and name = 'Prewitt edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 20 and name = 'Canny edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 30 and name = 'Hough standard (STD)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 31 and name = 'Kernel-based Hough transform (KHT)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 41 and name = 'Standard Histogram of oriented gradients (S-HOG)'...
*[COMPV INFO]: [CompVMatcher] Registering matcher factory with id = 0 and name = 'Brute force matcher'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 1 and name = 'PLSL (Parallel Light Speed Labeling)'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 19 and name = 'LMSER (Linear Time Maximally Stable Extremal Regions)'...
*[COMPV INFO]: [CompVGL] Initializing [gl] module (v 1.0.0)...
*[COMPV INFO]: [CompVGL] GL module initialized
*[COMPV INFO]: [CompVGpu] Initializing [gpu] module (v 1.0.0)...
*[COMPV INFO]: [CompVSharedLib] Loading shared library from nvcuda.dll
*[COMPV INFO]: [CompVGpu] Failed to open CUDA lib
*[COMPV INFO]: [CompVCamera] Initializing [camera] module (v 1.0.0)...
*[COMPV INFO]: [CompVCamera] Camera plugin path: C:\Users\USER\Documents\ultimateALPR-SDK\samples\python\recognizer\CompVPluginMFoundation.dll
*[COMPV INFO]: [CompVDrawing] Initializing [drawing] module (v 1.0.0)...
*[COMPV INFO]: [CompVDrawing] /!\ No jpeg decoder found
*[COMPV INFO]: [CompVDrawing] Drawing module initialized
*[COMPV INFO]: [CompVGpu] GPU enabled: true
*[COMPV INFO]: /!\ Code in file 'source\ultimate_base_engine.cxx' in function 'ultimateBase::UltBaseEngine::init' starting at line #75: Not optimized for GPU -> GPGPU computing not enabled or deactivated
*[COMPV INFO]: [UltBaseOpenCL] Trying to load [OpenCL.dll]
*[COMPV INFO]: [CompVSharedLib] Loading shared library from OpenCL.dll
*[COMPV INFO]: [UltBaseOpenCL] Loaded [OpenCL.dll], looksLikeValid: yes...
*[COMPV INFO]: [UltBaseOpenCLUtils] Selected platform vendor: Intel(R) Corporation
*[COMPV INFO]: [UltBaseOpenCLUtils] deviceCount=1
*[COMPV INFO]: [UltBaseOpenCLUtils] Device -> name: Intel(R) HD Graphics 520, id: 0000017A3F69CDE0
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT=1
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE=1
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_COMPUTE_UNITS=24
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS=3
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_WORK_ITEM_SIZES=256, 256, 256,
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_WORK_GROUP_SIZE=256
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_CLOCK_FREQUENCY=1000 MHz
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE=64 B
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_GLOBAL_MEM_SIZE=3375353856 B (3218 MB)
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_LOCAL_MEM_SIZE=65536 B (64 KB)
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_MEM_ALLOC_SIZE=1609 MB
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_PLATFORM_VERSION=OpenCL 2.1
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_VERSION=OpenCL 2.1 NEO
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DRIVER_VERSION=27.20.100.8681
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_OPENCL_C_VERSION=OpenCL C 2.0
***[COMPV ERROR]: function: "ultimateBase::UltBaseOpenCLUtils::init()"
file: "source\opencl\ultimate_base_opencl_utils.cxx"
line: "96"
message: [UltBaseOpenCLUtils] OpenCL operation failed (-30 -> CL_INVALID_VALUE) ->
***[COMPV ERROR]: function: "ultimateBase::UltBaseOpenCLUtils::init()"
file: "source\opencl\ultimate_base_opencl_utils.cxx"
line: "106"
message: Operation Failed (COMPV_ERROR_CODE_E_UNKNOWN) ->
*[COMPV INFO]: [UltBaseOpenCL] Failed to hook functions using [OpenCL.dll] library
*[COMPV INFO]: [UltOcrEngine] Tensorflow version: 1.15.0
*[COMPV INFO]: [UltAlprPlugin] Loading plugin: ultimatePluginOpenVino.dll ...
*[COMPV INFO]: [CompVSharedLib] Loading shared library from ultimatePluginOpenVino.dll
***[COMPV ERROR]: function: "compv::CompVSharedLib::open()"
file: "compv_sharedlib.cxx"
line: "69"
message: [CompVSharedLib] Failed to load library with path=ultimatePluginOpenVino.dll, Error: 0x0000007e
***[COMPV ERROR]: function: "compv::CompVSharedLib::open()"
file: "compv_sharedlib.cxx"
line: "73"
message: Operation Failed (COMPV_ERROR_CODE_E_NOT_FOUND) ->
***[COMPV ERROR]: function: "compv::CompVSharedLib::newObj()"
file: "compv_sharedlib.cxx"
line: "119"
message: Operation Failed (COMPV_ERROR_CODE_E_NOT_FOUND) ->
***[COMPV ERROR]: function: "ultimateAlpr::UltAlprPlugin::load()"
file: "source\ultimate_alpr_plugin.cxx"
line: "95"
message: Operation Failed (COMPV_ERROR_CODE_E_NOT_FOUND) ->
*[COMPV INFO]: [UltAlprSdkEnginePrivate]**** Copyright (C) 2011-2024 Doubango Telecom <https://www.doubango.org> ****
You're using an unlicensed version of ultimateALPR-SDK <https://github.com/DoubangoTelecom/ultimateALPR-SDK>
without the rights to include the SDK in any form of commercial product.
*[COMPV INFO]: [UltAlprSdkEnginePrivate]Is CUDA correctly configured: No
*[COMPV INFO]: [UltAlprSdkEnginePrivate]IC took 79 millis
*[COMPV INFO]: [CompVCpu] Enabling asm code
*[COMPV INFO]: [CompVCpu] Enabling intrinsic code
*[COMPV INFO]: [UltAlprSdkEnginePrivate]recogn_tf_num_threads: 4, acceleration backend: OpenVino,
*[COMPV INFO]: [UltAlprRecognizer] TensorRT not enabled, do not create the plugin for the OCR model.
*[COMPV INFO]: [UltOcrRecognizer] Your OCR module is neither GPU nor NPU optimized.
*[COMPV INFO]: [UltOcrTensorflowSessionOptions] gpu_memory_alloc_max_percent = 0.100000
*[COMPV INFO]: [UltOcrTensorflowSessionOptions] Alloc session with gpu_memory_alloc_max_percent = 10%
*[COMPV INFO]: [UltOcrRecognizer] OCR module backend: Tensorflow
*[COMPV INFO]: [UltOcrTensorflowSessionOptions] gpu_memory_alloc_max_percent = 0.100000
*[COMPV INFO]: [UltOcrTensorflowSessionOptions] Alloc session with gpu_memory_alloc_max_percent = 10%
*[COMPV INFO]: [UltOcrTensorflowSessionOptions] gpu_memory_alloc_max_percent = 0.250000
*[COMPV INFO]: [UltOcrTensorflowSessionOptions] Alloc session with gpu_memory_alloc_max_percent = 20%
[PythonRecognizer] Init: OK -> {}
*[COMPV INFO]: /!\ Code in file 'compv_mem.cxx' in function 'compv::CompVMemCopy_C' starting at line #985: Not optimized -> No SIMD implementation found. On ARM consider http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka13544.html
*[COMPV INFO]: /!\ Code in file 'image\compv_image_conv_to_rgbx.cxx' in function 'compv::CompVImageConvToRGBx::rgbx' starting at line #560: Not optimized -> No in-place conversion found for BGRA32/BGR24 -> RGB24. You should consider using RGBA32/RGB24 instead of BGRA32/BGR24
*[COMPV INFO]: /!\ Code in file 'source\ultimate_alpr_detector.cxx' in function 'ultimateAlpr::UltAlprDetector::process' starting at line #29: Not optimized -> Batching will not be activated for this function
*[COMPV INFO]: /!\ Code in file 'source\ultimate_ocr_tensorflow_session_detect.cxx' in function 'ultimateOcr::UltOcrTensorflowSessionDetector::processInternal' starting at line #116: Not optimized -> Batching not supported for this function
*[COMPV INFO]: /!\ Code in file 'intrin\x86\compv_mem_intrin_ssse3.cxx' in function 'compv::CompVMemUnpack3_SrcPtrNotAligned_Intrin_SSSE3' starting at line #69: Not built with SSSE3 support
*[COMPV INFO]: [UltAlprSdkEngine]Call: ultimateAlprSdk::UltAlprSdkEngine::deInit
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [Thread] Thread with id=0000000000002F74 will join
*[COMPV INFO]: [CompVMem] compv::CompVMem::poolCleanBuffersForCurrentThread(threadId:0000000000002F74)
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(threadId:0000000000002F74) - EXIT
*[COMPV INFO]: Thread with id=0000000000002F74 will join
*[COMPV INFO]: [Thread] ***Thread with id=0000000000002F74 destroyed***
*[COMPV INFO]: [Thread] Thread with id=00000000000017CC will join
*[COMPV INFO]: [CompVMem] compv::CompVMem::poolCleanBuffersForCurrentThread(threadId:00000000000017CC)
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(threadId:00000000000017CC) - EXIT
*[COMPV INFO]: Thread with id=00000000000017CC will join
*[COMPV INFO]: [Thread] ***Thread with id=00000000000017CC destroyed***
*[COMPV INFO]: [Thread] Thread with id=0000000000003144 will join
*[COMPV INFO]: [CompVMem] compv::CompVMem::poolCleanBuffersForCurrentThread(threadId:0000000000003144)
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(threadId:0000000000003144) - EXIT
*[COMPV INFO]: Thread with id=0000000000003144 will join
*[COMPV INFO]: [Thread] ***Thread with id=0000000000003144 destroyed***
*[COMPV INFO]: [Thread] Thread with id=0000000000003FBC will join
*[COMPV INFO]: [CompVMem] compv::CompVMem::poolCleanBuffersForCurrentThread(threadId:0000000000003FBC)
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(threadId:0000000000003FBC) - EXIT
*[COMPV INFO]: Thread with id=0000000000003FBC will join
*[COMPV INFO]: [Thread] ***Thread with id=0000000000003FBC destroyed***
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: Drawing module deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
*[COMPV INFO]: [CompVBase] DeInitializing base modules (v 1.0.0)...
*[COMPV INFO]: [CompVBase] Base modules deinitialized
[PythonRecognizer] DeInit: OK -> {}
Traceback (most recent call last):
  File "recognizer.py", line 140, in <module>
    process_video(args.video)
  File "recognizer.py", line 107, in process_video
    if result.get("plates"):
  File "C:\Users\USER\Documents\ultimateALPR-SDK\python\ultimateAlprSdk.py", line 95, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, UltAlprSdkResult, name)
  File "C:\Users\USER\Documents\ultimateALPR-SDK\python\ultimateAlprSdk.py", line 55, in _swig_getattr
    raise AttributeError(name)
AttributeError: get

**Comment by asuzairy** [comment]
solution?
